### ISSUE TITLE
Updating issue: invalid new-expression of abstract class type 'esphome::mhi::SetExternalRoomTemperatureAction<float>'

### ISSUE THREAD

**Issue by FoUStep** [ginkage/MHI-AC-Ctrl-ESPHome#185]
Hello,

After updating ESPHome to 2025.11.0 installing (updating) the version to the ESP8266 device fails:
```
src/main.cpp: In function 'void setup()':
src/main.cpp:934:112: error: invalid new-expression of abstract class type 'esphome::mhi::SetExternalRoomTemperatureAction<float>'
  934 |   mhi_setexternalroomtemperatureaction_id = new mhi::SetExternalRoomTemperatureAction<float>(mhi_mhiplatform_id);
      |                                                                                                                ^
In file included from src/esphome.h:4,
                 from src/main.cpp:3:
src/esphome/components/MhiAcCtrl/automation.h:41:32: note:   because the following virtual functions are pure within 'esphome::mhi::SetExternalRoomTemperatureAction<float>':
   41 | template<typename... Ts> class SetExternalRoomTemperatureAction : public Action<Ts...> {
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/components/MhiAcCtrl/automation.h:3,
                 from src/esphome.h:4,
                 from src/main.cpp:3:
src/esphome/core/automation.h:225:16: note:     'void esphome::Action<Ts>::play(const Ts& ...) [with Ts = {float}]'
  225 |   virtual void play(const Ts &...x) = 0;
      |                ^~~~
*** [.pioenvs/mhi_woonkamer/src/main.cpp.o] Error 1
========================== [FAILED] Took 3.62 seconds ==========================
```

Board info:
```
esp8266:
  board: d1_mini

external_components:
  - source: github://ginkage/MHI-AC-Ctrl-ESPHome@master
    components: [MhiAcCtrl]
```

Any idea why it's a invalid new-expression which worked with the previous versions (2025.10.X)? The config is valid according to ESPHome. Running v4.2.

**Comment by hmmbob** [comment]
> Could it be this part?

No, ESPHome 2025.11 has a major overhaul over the automation and climate frameworks - meaning the C source code. 

See the first **6** items at https://developers.esphome.io/blog/ to get a feeling on the overhaul. 

-- edit

@ginkage Might be wise to pin this issue and to change title to clearly indicate that upgrading to ESPHome 2025.11 will trigger multiple errors and warnings at the moment.

**Comment by hmmbob** [comment]
I've just installed it on one of our 4 ac's and tested with HA: works fine & as expected, without any errors.
