### ISSUE TITLE
Errors when updating to V4

### ISSUE THREAD

**Issue by JoepWi** [ginkage/MHI-AC-Ctrl-ESPHome#149]
Can anybody tell me what I'm doing wrong.

I get this errors when changing my config for V4 (simple variant)

`INFO ESPHome 2025.4.2
INFO Reading configuration /config/esphome/airco-joep.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing airco-joep (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 160MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.6
Linking .pioenvs/airco-joep/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_Z13calc_checksumPh':
MHI-AC-Ctrl-core.cpp:(.text._Z13calc_checksumPh+0x0): multiple definition of `_Z13calc_checksumPh'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._Z13calc_checksumPh+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core16reset_old_valuesEv':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16reset_old_valuesEv+0x8): multiple definition of `_ZN16MHI_AC_Ctrl_Core16reset_old_valuesEv'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16reset_old_valuesEv+0x4): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core4initEv':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core4initEv+0x10): multiple definition of `_ZN16MHI_AC_Ctrl_Core4initEv'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core4initEv+0x10): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core9set_powerEb':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_powerEb+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core9set_powerEb'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_powerEb+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core8set_modeE6ACMode':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core8set_modeE6ACMode+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core8set_modeE6ACMode'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core8set_modeE6ACMode+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core13set_tsetpointEj':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core13set_tsetpointEj+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core13set_tsetpointEj'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core13set_tsetpointEj+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core7set_fanEj':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core7set_fanEj+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core7set_fanEj'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core7set_fanEj+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core9set_vanesEj':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_vanesEj+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core9set_vanesEj'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_vanesEj+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core17request_ErrOpDataEv':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core17request_ErrOpDataEv+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core17request_ErrOpDataEv'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core17request_ErrOpDataEv+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core9set_troomEh':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_troomEh+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core9set_troomEh'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core9set_troomEh+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core16get_troom_offsetEv':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16get_troom_offsetEv+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core16get_troom_offsetEv'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16get_troom_offsetEv+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core16set_troom_offsetEf':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16set_troom_offsetEf+0x0): multiple definition of `_ZN16MHI_AC_Ctrl_Core16set_troom_offsetEf'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core16set_troom_offsetEf+0x0): first defined here
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/airco-joep/src/esphome/components/MhiAcCtrl/MHI-AC-Ctrl-core.cpp.o: in function `_ZN16MHI_AC_Ctrl_Core4loopEj':
MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core4loopEj+0x80): multiple definition of `_ZN16MHI_AC_Ctrl_Core4loopEj'; .pioenvs/airco-joep/src/MHI-AC-Ctrl-core.cpp.o:MHI-AC-Ctrl-core.cpp:(.text._ZN16MHI_AC_Ctrl_Core4loopEj+0x78): first defined here
collect2: error: ld returned 1 exit status
*** [.pioenvs/airco-joep/firmware.elf] Error 1
========================== [FAILED] Took 1.97 seconds ==========================`

**Comment by oliv3r** [comment]
You probably need to 'clean' your build files, it's probably re-using some previous compiled object files that it shouldn't?
